# Generated by Django 5.2 on 2025-04-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('class_name', models.CharField(max_length=20)),
                ('marks', models.FloatField(max_length=30)),
            ],
        ),
    ]
